CREATE TABLE IF NOT EXISTS users (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     email VARCHAR(254) UNIQUE NOT NULL,
     name VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories(
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     annotation VARCHAR(2000) NOT NULL,
     description VARCHAR(7000) NOT NULL,
     event_date TIMESTAMP NOT NULL,
     lat DOUBLE PRECISION NOT NULL,
     lon DOUBLE PRECISION NOT NULL,
     paid BOOLEAN,
     participant_limit BIGINT,
     request_moderation BOOLEAN,
     title VARCHAR(120) NOT NULL,
     state VARCHAR(20) NOT NULL DEFAULT 'PENDING',
     created_on TIMESTAMP NOT NULL,
     published_on TIMESTAMP,
     category_id BIGINT NOT NULL,
     initiator_id BIGINT NOT NULL,
     FOREIGN KEY (category_id) REFERENCES categories(id),
     FOREIGN KEY (initiator_id) REFERENCES users(id)
     );

CREATE TABLE IF NOT EXISTS compilations (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     title VARCHAR(50) NOT NULL,
     pinned BOOLEAN NOT NULL DEFAULT FALSE
   );

CREATE TABLE IF NOT EXISTS participation_requests (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     created TIMESTAMP NOT NULL,
     status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
     event_id BIGINT NOT NULL,
     request_id BIGINT NOT NULL,
     FOREIGN KEY (event_id) REFERENCES events(id),
     FOREIGN KEY (request_id) REFERENCES users(id),
     UNIQUE (event_id, request_id)
   );

   CREATE TABLE IF NOT EXISTS compilation_events(
     PRIMARY KEY (compilation_id, event_id),
     compilation_id BIGINT NOT NULL,
     event_id BIGINT NOT NULL,
     FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
     FOREIGN KEY (compilation_id) REFERENCES compilations(id) ON DELETE CASCADE
  );

  CREATE TABLE IF NOT EXISTS comments
  (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      text TEXT NOT NULL,
      author_id BIGINT NOT NULL,
      event_id BIGINT NOT NULL,
      created_on TIMESTAMP NOT NULL,
      updated_on TIMESTAMP,
      FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE,
      FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
  );